// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileRequest struct {
	FileKey string `protobuf:"bytes,1,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	// metadata will only return on -1 and 0
	Block                uint32   `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}
func (*FileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *FileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequest.Unmarshal(m, b)
}
func (m *FileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequest.Marshal(b, m, deterministic)
}
func (m *FileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequest.Merge(m, src)
}
func (m *FileRequest) XXX_Size() int {
	return xxx_messageInfo_FileRequest.Size(m)
}
func (m *FileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequest proto.InternalMessageInfo

func (m *FileRequest) GetFileKey() string {
	if m != nil {
		return m.FileKey
	}
	return ""
}

func (m *FileRequest) GetBlock() uint32 {
	if m != nil {
		return m.Block
	}
	return 0
}

type FileRequestMessage struct {
	// Allows chunking of requests :)
	Req                  []*FileRequest `protobuf:"bytes,1,rep,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FileRequestMessage) Reset()         { *m = FileRequestMessage{} }
func (m *FileRequestMessage) String() string { return proto.CompactTextString(m) }
func (*FileRequestMessage) ProtoMessage()    {}
func (*FileRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *FileRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequestMessage.Unmarshal(m, b)
}
func (m *FileRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequestMessage.Marshal(b, m, deterministic)
}
func (m *FileRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequestMessage.Merge(m, src)
}
func (m *FileRequestMessage) XXX_Size() int {
	return xxx_messageInfo_FileRequestMessage.Size(m)
}
func (m *FileRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequestMessage proto.InternalMessageInfo

func (m *FileRequestMessage) GetReq() []*FileRequest {
	if m != nil {
		return m.Req
	}
	return nil
}

type FileResponse struct {
	FileKey              string   `protobuf:"bytes,1,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	Block                uint32   `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	MimeType             string   `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileResponse) Reset()         { *m = FileResponse{} }
func (m *FileResponse) String() string { return proto.CompactTextString(m) }
func (*FileResponse) ProtoMessage()    {}
func (*FileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *FileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileResponse.Unmarshal(m, b)
}
func (m *FileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileResponse.Marshal(b, m, deterministic)
}
func (m *FileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileResponse.Merge(m, src)
}
func (m *FileResponse) XXX_Size() int {
	return xxx_messageInfo_FileResponse.Size(m)
}
func (m *FileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileResponse proto.InternalMessageInfo

func (m *FileResponse) GetFileKey() string {
	if m != nil {
		return m.FileKey
	}
	return ""
}

func (m *FileResponse) GetBlock() uint32 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *FileResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *FileResponse) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

type FileResponseMessage struct {
	Res                  []*FileResponse `protobuf:"bytes,1,rep,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FileResponseMessage) Reset()         { *m = FileResponseMessage{} }
func (m *FileResponseMessage) String() string { return proto.CompactTextString(m) }
func (*FileResponseMessage) ProtoMessage()    {}
func (*FileResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *FileResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileResponseMessage.Unmarshal(m, b)
}
func (m *FileResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileResponseMessage.Marshal(b, m, deterministic)
}
func (m *FileResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileResponseMessage.Merge(m, src)
}
func (m *FileResponseMessage) XXX_Size() int {
	return xxx_messageInfo_FileResponseMessage.Size(m)
}
func (m *FileResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FileResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FileResponseMessage proto.InternalMessageInfo

func (m *FileResponseMessage) GetRes() []*FileResponse {
	if m != nil {
		return m.Res
	}
	return nil
}

func init() {
	proto.RegisterType((*FileRequest)(nil), "api.FileRequest")
	proto.RegisterType((*FileRequestMessage)(nil), "api.FileRequestMessage")
	proto.RegisterType((*FileResponse)(nil), "api.FileResponse")
	proto.RegisterType((*FileResponseMessage)(nil), "api.FileResponseMessage")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x06, 0x32, 0x95, 0xec, 0xb8, 0xb8, 0xdd, 0x32, 0x73,
	0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x24, 0xb9, 0x38, 0xd2, 0x80, 0xdc, 0xf8,
	0xec, 0xd4, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x76, 0x10, 0xdf, 0x3b, 0xb5, 0x52,
	0x48, 0x84, 0x8b, 0x35, 0x29, 0x27, 0x3f, 0x39, 0x5b, 0x82, 0x09, 0x28, 0xce, 0x1b, 0x04, 0xe1,
	0x28, 0x59, 0x70, 0x09, 0x21, 0xe9, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x52, 0xe2,
	0x62, 0x2e, 0x4a, 0x2d, 0x04, 0x9a, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa0, 0x07, 0xb2, 0x13, 0x49,
	0x55, 0x10, 0x48, 0x52, 0xa9, 0x80, 0x8b, 0x07, 0x22, 0x56, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x4a,
	0xb2, 0xd5, 0x42, 0x42, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x12, 0xcc, 0x40, 0x41, 0x9e, 0x20,
	0x30, 0x5b, 0x48, 0x9a, 0x8b, 0x33, 0x37, 0x33, 0x37, 0x35, 0xbe, 0xa4, 0xb2, 0x20, 0x55, 0x82,
	0x05, 0x6c, 0x0a, 0x07, 0x48, 0x20, 0x04, 0xc8, 0x57, 0xb2, 0xe2, 0x12, 0x46, 0xb6, 0x11, 0xe6,
	0x58, 0x65, 0x90, 0x63, 0x8b, 0xa1, 0x8e, 0x15, 0x44, 0x72, 0x2c, 0x44, 0x19, 0xc8, 0xb5, 0xc5,
	0x46, 0xce, 0x5c, 0x2c, 0x20, 0x41, 0x21, 0x6b, 0x2e, 0x96, 0xe0, 0xd4, 0xbc, 0x14, 0x21, 0x71,
	0x74, 0x4f, 0x41, 0x4d, 0x93, 0x92, 0xc0, 0x30, 0x00, 0x2a, 0xa3, 0xc4, 0x90, 0xc4, 0x06, 0x0e,
	0x78, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x63, 0xe5, 0x6a, 0x85, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FileClient is the client API for File service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileClient interface {
	Send(ctx context.Context, in *FileRequestMessage, opts ...grpc.CallOption) (*FileResponseMessage, error)
}

type fileClient struct {
	cc grpc.ClientConnInterface
}

func NewFileClient(cc grpc.ClientConnInterface) FileClient {
	return &fileClient{cc}
}

func (c *fileClient) Send(ctx context.Context, in *FileRequestMessage, opts ...grpc.CallOption) (*FileResponseMessage, error) {
	out := new(FileResponseMessage)
	err := c.cc.Invoke(ctx, "/api.File/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServer is the server API for File service.
type FileServer interface {
	Send(context.Context, *FileRequestMessage) (*FileResponseMessage, error)
}

// UnimplementedFileServer can be embedded to have forward compatible implementations.
type UnimplementedFileServer struct {
}

func (*UnimplementedFileServer) Send(ctx context.Context, req *FileRequestMessage) (*FileResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}

func RegisterFileServer(s *grpc.Server, srv FileServer) {
	s.RegisterService(&_File_serviceDesc, srv)
}

func _File_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.File/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).Send(ctx, req.(*FileRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _File_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.File",
	HandlerType: (*FileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _File_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
